// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/Layout/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Layout/Breadcrumb/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Layout/Footer/index.vue')['default']
    Hamburger: typeof import('./src/components/Layout/Hamburger/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    NavAvatar: typeof import('./src/components/Layout/NavBar/components/NavAvatar.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar/index.vue')['default']
    NavRight: typeof import('./src/components/Layout/NavBar/components/NavRight.vue')['default']
    SideBar: typeof import('./src/components/Layout/SideBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ThemePicker: typeof import('./src/components/Layout/NavBar/components/ThemePicker.vue')['default']
    UpdatePassword: typeof import('./src/components/Layout/NavBar/components/UpdatePassword.vue')['default']
    UpdateUserInfo: typeof import('./src/components/Layout/NavBar/components/UpdateUserInfo.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/index.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
    ValidCode: typeof import('./src/components/ValidCode/index.vue')['default']
    ViewerImg: typeof import('./src/components/ViewerImg/index.vue')['default']
  }
}

export { }
