// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/Layout/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Layout/Breadcrumb/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer/index.vue')['default']
    Hamburger: typeof import('./src/components/Layout/Hamburger/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/index.vue')['default']
    NavAvatar: typeof import('./src/components/Layout/NavBar/components/NavAvatar.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar/index.vue')['default']
    NavRight: typeof import('./src/components/Layout/NavBar/components/NavRight.vue')['default']
    NoData: typeof import('./src/components/NoData/index.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading/index.vue')['default']
    SideBar: typeof import('./src/components/Layout/SideBar/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ThemePicker: typeof import('./src/components/Layout/NavBar/components/ThemePicker.vue')['default']
    UpdatePassword: typeof import('./src/components/Layout/NavBar/components/UpdatePassword.vue')['default']
    UpdateUserInfo: typeof import('./src/components/Layout/NavBar/components/UpdateUserInfo.vue')['default']
    UploadAvatar: typeof import('./src/components/UploadAvatar/index.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
    ValidCode: typeof import('./src/components/ValidCode/index.vue')['default']
    ViewerImg: typeof import('./src/components/ViewerImg/index.vue')['default']
  }
}

export { }
